/** E2E Demo: Documents — upload, list, extraction status, expand details. */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';
import { screenshot, resetScreenshotCounter, waitForAPI, cleanupDocuments, pace } from './helpers';

// Path to test PDFs generated by generate_test_docs.py
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEST_DOCS_DIR = path.resolve(__dirname, '../../backend/test_docs/financial');

test.describe('Document Upload & Management', () => {
  test.beforeAll(async () => {
    await waitForAPI();
    await cleanupDocuments();
  });

  test.beforeEach(() => {
    resetScreenshotCounter();
  });

  test('upload documents and view extraction results', async ({ page }) => {
    // Increase timeout for this test — uploads + extraction can be slow
    test.setTimeout(90_000);

    await page.goto('/profile/documents');
    await page.waitForLoadState('networkidle');

    // ── Initial State ──
    await expect(page.locator('.app-shell-content h1')).toHaveText('My Documents');
    await screenshot(page, 'documents-landing');

    // Check if test PDFs exist
    const preApprovalPath = path.join(TEST_DOCS_DIR, 'sample_pre_approval.pdf');
    const bankStatementPath = path.join(TEST_DOCS_DIR, 'sample_bank_statement.pdf');
    const payStubPath = path.join(TEST_DOCS_DIR, 'sample_pay_stub.pdf');
    const taxReturnPath = path.join(TEST_DOCS_DIR, 'sample_tax_return.pdf');
    const w2Path = path.join(TEST_DOCS_DIR, 'sample_w2.pdf');

    if (!fs.existsSync(preApprovalPath)) {
      test.skip(true, 'Test PDFs not found — run `python generate_test_docs.py` first');
      return;
    }

    // Helper: upload a document and wait for card to appear
    const uploadDoc = async (docType: string, filePath: string, expectedCount: number) => {
      // Select doc type
      await page.locator('.upload-section select').selectOption(docType);
      await pace(300);

      // Wait for file input to be enabled (not uploading)
      const fileInput = page.locator('input[type="file"]');
      await fileInput.setInputFiles(filePath);

      // Wait for the document card count to reach expected
      await expect(page.locator('.document-card')).toHaveCount(expectedCount, { timeout: 20000 });
      await pace(500);
    };

    // ── Upload Pre-Approval Letter ──
    await uploadDoc('pre_approval_letter', preApprovalPath, 1);
    await screenshot(page, 'documents-after-pre-approval-upload');

    // Click to expand the first document card
    await page.locator('.document-card-header').first().click();
    await pace();
    await screenshot(page, 'documents-pre-approval-expanded');

    // Collapse it before next upload
    await page.locator('.document-card-header').first().click();
    await pace(300);

    // ── Upload Bank Statement ──
    await uploadDoc('bank_statement', bankStatementPath, 2);
    await screenshot(page, 'documents-after-bank-statement-upload');

    // ── Upload Pay Stub ──
    await uploadDoc('pay_stub', payStubPath, 3);
    await screenshot(page, 'documents-after-pay-stub-upload');

    // ── Upload Tax Return ──
    await uploadDoc('tax_return', taxReturnPath, 4);
    await screenshot(page, 'documents-after-tax-return-upload');

    // ── Upload W-2 ──
    await uploadDoc('w2', w2Path, 5);
    await screenshot(page, 'documents-after-w2-upload');

    // ── Final State ──
    const docCards = page.locator('.document-card');
    const count = await docCards.count();
    expect(count).toBeGreaterThanOrEqual(5);
    await screenshot(page, 'documents-all-uploaded');

    // Expand each card to show extraction results
    for (let i = 0; i < Math.min(count, 5); i++) {
      const header = docCards.nth(i).locator('.document-card-header');
      await header.click();
      await pace(300);
    }
    await screenshot(page, 'documents-all-expanded');
  });
});
